<a href="https://colab.research.google.com/github/JakubPac/kurs_ml/blob/main/gradient_descet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m= len(X1)

In [5]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [6]:
Y

array([[3000],
       [3250],
       [3500],
       [3750],
       [4000],
       [4250]])

In [7]:
bias = np.ones((m, 1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [8]:
X = np.append(bias, X1, axis = 1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

losowa inicjalizacja parametrów

In [9]:
eta = 0.01
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[-0.87899714]
 [ 1.1714377 ]]


metoda gradientu prostego

In [10]:
intercept = []
coef = []

for i in range(3000):
  gradient = (2/m) * X.T.dot(X.dot(weights)- Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2749.95598141]
 [ 250.01028184]]


In [11]:
df = pd.DataFrame(data = {'intercept' : intercept, 'coef' : coef})
df.head()

intercept        coef
0   71.556582  269.210965
1  123.780683  450.874678
2  162.243842  573.778045
3  191.334502  656.708302
4  214.038231  712.446702

wizualizacja dopasowania

In [13]:
px.line(df, y = 'intercept', width = 800, title = 'Dopasowanie : intercept')

In [14]:
px.line(df, y = 'coef', width = 800, title = 'Dopasowanie : coef')